wandb:
  project: '2025'
  entity: ${oc.env:WANDB_USER, "user"}
  group: ${oc.env:WANDB_GROUP, "lux_s3_experiments"}
act_space: BasicActionSpace
obs_space: Obs3
reward_space: GameResultReward
enable_game_early_stop: false
enable_multiplier_scaling: false
five_rounds: true
flip_learning: true
flip_axes: true
enable_sap_masks: false
use_GPT_losses: false
zero_energy_on_invalidation: false
use_old_input: false
disable_wandb: false
debug: false
total_steps: 200000000.0
unroll_length: 16
discounting: 0.999
clip_grads: 0
optimizer_class: Adam
optimizer_kwargs:
  lr: 1.0e-05
  eps: 0.0003
min_lr_mod: 0.01
enable_lr_scheduler: true
lr_lambda: 1
lr_lambda_change_per_step: -5.0e-09
baseline_cost: 1.0
lmb: 0.9
reduction: mean
stats_freq_batches: 1
sharing_strategy: file_descriptor
replay: false
kaggle: false
benchmark_baseline_dir: ./models/01_03_test_x8_cont_7/
benchmark_baseline_file: 200000000_weights.pt
competitors_dir: ./outputs/03-06/16-17-09/
num_competitors: 50
num_bench_envs: 20
fixed_baseline: true
rerun: false
start_from_checkpoint: 240168320_weights.pt
games_to_test: 1000
enable_resnet: true
enable_lstm: true
lstm_k_size: 3
enable_transformer: false
n_transformer_blocks: 1
use_baseline_v2: true
enable_transformer_v2: true
n_transformer_v2_blocks: 4
transformer_dim_head: 32
one_prediction_head: true
enable_per_unit_resnet: true
enable_se_in_per_unit_resnet: false
use_embedding_input: false
name: tune_against_mask_cont
use_bf16: true
num_actors: 100
num_buffers: 150
num_stats_buffers: 16
n_actor_envs: 20
batch_size: 20
n_batch_prepare_processes: 2
prepare_batches: 3
model_arch: conv_model
n_blocks: 24
hidden_dim: 128
embedding_dim: 32
n_merge_layers: 1
normalize: false
kernel_size: 5
prediction_cost: 1.0
target_entropy_worker: 0.15
target_entropy_worker_change_per_step: -7.5e-10
target_entropy_sapper: 0.4
target_entropy_sapper_change_per_step: -2.0e-09
entropy_initial_multiplier_worker: 0.001
entropy_initial_multiplier_sapper: 0.01
entropy_mult_change_speed_per_step: 8.0e-07
use_teacher: true
use_old_teacher_loss: false
only_teacher_loss: false
frozen_teacher_both_sides: false
frozen_teacher_sample: false
teacher_load_dir: ./models/07_03_tune_against_mask/
teacher_checkpoint_file: 300000000_weights.pt
teacher_kl_cost: 0.01
teacher_kl_cost_change_per_step: 0
teacher_baseline_cost: 0
imitation_cost: 0.0
n_learner_devices: 4
n_actor_devices: 4
update_actor_weigts_every_batches: 1
load_dir: ./models/07_03_tune_against_mask/
checkpoint_file: 300000000_weights.pt
weights_only: true
load_optimizer: false
n_warmup_steps: 1000000
frozen_actor_checkpoint_paths:
- ./models/06_03_mask_exp/200000000_weights.pt
change_frozen_actor_every_n_iters: 1000
num_frozen_model_actors: 33
num_frozen_model_actors_buffers: 50
frozen_teacher_actors: 33
frozen_teacher_models_buffers: 50
behavior_cloning_actors: 0
behavior_cloning_actors_buffers: 0
frozen_actor_probability: 0.33
frozen_teacher_probability: 0.33
behavior_cloning_probability: 0.0
selfplay_probability: 1.0
seed: null
obs_space_kwargs: {}
reward_space_kwargs: {}
checkpoint_freq: 5.0
num_learner_threads: 1
